Python 3.7 doesn't work due to PCRaster
So prevent using that. Otherwise you get this:

ImportError: The 'pcraster' module was built for Python 3.6, the version used is 3.7