Update environment.yml
with cftime version 1.1 this error occurs (need to check, for now set to 1.0.4):
  File "..\wflow\wf_netcdfio.py", line 730, in gettimestep
    tzinfo=None
  File "cftime\_cftime.pyx", line 1305, in cftime._cftime.datetime.replace
  File "cftime\_cftime.pyx", line 1564, in cftime._cftime.DatetimeGregorian.__init__
  File "cftime\_cftime.pyx", line 1257, in cftime._cftime.datetime.__init__
TypeError: __init__() got an unexpected keyword argument 'tzinfo'